CREATE TABLE IF NOT EXISTS users (
    userId       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR       NOT NULL UNIQUE,
    login        VARCHAR       NOT NULL UNIQUE,
    name         VARCHAR       ,
    birthday     dateTime
);

CREATE TABLE IF NOT EXISTS mpaRating (
    ratingId     INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ratingName   VARCHAR       NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    filmId       INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR       NOT NULL,
    description  VARCHAR(200)  NOT NULL,
    releaseDate  dateTime      NOT NULL,
    duration     INTEGER       NOT NULL,
    ratingId     INTEGER       REFERENCES mpaRating (ratingId) NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
    userId       INTEGER       REFERENCES users (userId),
    otherUserId  INTEGER       REFERENCES users (userId)
--    PRIMARY KEY (userId, otherUserId)
);

CREATE TABLE IF NOT EXISTS usersWhoLiked (
    userId       INTEGER       REFERENCES users (userId),
    filmId       INTEGER       REFERENCES films (filmId)
);

CREATE TABLE IF NOT EXISTS genres (
    genreId      INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS filmGenres (
    genreId      INTEGER       REFERENCES genres (genreId),
    filmId       INTEGER       REFERENCES films (filmId),
    PRIMARY KEY (genreId, filmId)
);
